config/routes.rb
Rails.application.routes.draw do
  resources :uploads_controllers
  resources :uploads
  root to: 'uploads#index'
   namespace :api do
    namespace :v1 do
      resources :users, only: [:create]
      post '/login', to: 'auth#create'
      get '/profile', to: 'users#profile'
    end
  end

  # For controllers to use warp_controller, declare warp_resources here:
  warp_resources :documents, :changes, :portfolios
  resources :portfolios, only: [:index, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_one_attached :file
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :update, :destroy]

  # GET /uploads
  def index
    @uploads = Upload.all

    render json: @uploads
  end

  # GET /uploads/1
  def show
    render json: @upload
  end

  # POST /uploads
  def create
    @upload = Upload.new(upload_params)

    if @upload.save
      render json: @upload, status: :created, location: @upload
    else
      render json: @upload.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /uploads/1
  def update
    if @upload.update(upload_params)
      render json: @upload
    else
      render json: @upload.errors, status: :unprocessable_entity
    end
  end

  # DELETE /uploads/1
  def destroy
    @upload.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def upload_params
      params.require(:upload).permit(:title, :description, :portfolio_id, :isPublic, :file)
    end
end

app/views/uploads/_form.html.erb
<%= form_with(model: upload, local: true) do |form| %>

  <div class="upload_field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="upload_field">
    <%= form.label :file%>
    <%= form.file_field :file %>
  </div>

  <div class="upload_field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/uploads/show.html.erb
<strong> Title: </strong>
<%=  @upload.title %>

<%= link_to 'View file', @upload.file %>
<%= link_to 'Download', @upload.file download: '' %>

<strong> Description: </strong>
<%=  @upload.description %>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>